services:
  eve-bot:
    build: .
    container_name: eve-bot
    restart: unless-stopped
    volumes:
      - ./image_cache:/app/image_cache
      - ./killmail_images:/app/killmail_images
      - ./subscriptions.json:/app/subscriptions.json
      - ./logs:/app/logs
      - ./env:/app/.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"