version: '4.1'

services:
  eve-bot:
    build: .
    container_name: eve-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./subscriptions.json:/app/subscriptions.json
      - ./logs:/app/logs
      - ./env:/app/.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"